### ISSUE TITLE
AOSP June 2024 support

### ISSUE THREAD

**Issue by Jon8RFC** [Jon8RFC/NfcScreenOff#2]
A quick test shows that the NFC apk is still able to be patched.

**Comment by Jon8RFC** [comment]
It's actually a quick fix, unlike I originally thought.

Because of the NFC change (on my Pixel 8 Pro), I'm taking the time to do the first part of additional functionality, in case this happens again.  I'm slow at this, but I should have an initial release by June 22.

**Comment by Jon8RFC** [comment]
v2.1.0 released

This is working on my Pixel 8 Pro.
Please let me know if there are any new issues.
This was a large revamp, which is still a work in progress.

**Comment by LordSithek** [comment]
[NFCScreenOff_upload_this2.zip](https://github.com/user-attachments/files/15937250/NFCScreenOff_upload_this2.zip)
[KernelSU_install_log_2024-06-22-17-16-54.log](https://github.com/user-attachments/files/15937251/KernelSU_install_log_2024-06-22-17-16-54.log)
Hello, the process fails with KernelSU root, Xiaomi Mi Note 10, Android 14 DerpFest ROM. Similar result on realme GT Neo 2, also A14 DeroFest

**Comment by Jon8RFC** [comment]
> [NFCScreenOff_upload_this2.zip](https://github.com/user-attachments/files/15937250/NFCScreenOff_upload_this2.zip) [KernelSU_install_log_2024-06-22-17-16-54.log](https://github.com/user-attachments/files/15937251/KernelSU_install_log_2024-06-22-17-16-54.log) Hello, the process fails with KernelSU root, Xiaomi Mi Note 10, Android 14 DerpFest ROM. Similar result on realme GT Neo 2, also A14 DeroFest

Thanks for the report.  I think it's fixed, from what I've seen.
https://github.com/Jon8RFC/NfcScreenOff/releases

**Comment by LordSithek** [comment]
> > [NFCScreenOff_upload_this2.zip](https://github.com/user-attachments/files/15937250/NFCScreenOff_upload_this2.zip) [KernelSU_install_log_2024-06-22-17-16-54.log](https://github.com/user-attachments/files/15937251/KernelSU_install_log_2024-06-22-17-16-54.log) Hello, the process fails with KernelSU root, Xiaomi Mi Note 10, Android 14 DerpFest ROM. Similar result on realme GT Neo 2, also A14 DeroFest
> 
> Thanks for the report. I think it's fixed, from what I've seen. https://github.com/Jon8RFC/NfcScreenOff/releases

Thanks, can confirm its been installed on both my devices. Whenever possible, I will test the module 🤝

**Comment by Jon8RFC** [comment]
Seems like it's been good to go.
